batch_size: 10000            # track segments
event_batch_size: 8          # tpcs
write_batch_size: 1          # batches
is_spill_sim: 1              # boolean
spill_period: 1.2e6          # microseconds
event_separator: 'event_id'  # 'event_id'
tracks_dset_name: 'segments' # or 'segments'
max_events_per_file: 1000

max_light_truth_ids: 50 # set to zero to disable light truth backtracking
mc_truth_threshold: 0.1 # pe/us
