# Discussions of some of these parameters here:
# https://dunescience.slack.com/archives/C05BMKCBW3B/p1692623569387309
batch_size: 5000             # track segments
event_batch_size: 2          # tpcs
write_batch_size: 1          # batches
is_spill_sim: 1              # boolean
if_active_volume_check: 0    # boolean
spill_period: 1.2e6          # microseconds
event_separator: 'event_id'  # 'event_id'
tracks_dset_name: 'segments' # or 'segments'
max_events_per_file: 1000
