name: pm-login

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: [self-hosted, Linux]
    steps:
      - name: Checkout repository
        run: |
          echo $PWD
          echo "Starting job"
          mkdir runner; cd runner
          module load python/3.11
          echo $PWD
          echo "Checking out larnd-sim"
          git clone -b lar_runner --depth 1 https://github.com/DUNE/larnd-sim.git
          python3 -m venv env
          source ./env/bin/activate
          cd larnd-sim
          echo "Installing larnd-sim"
          pip install --upgrade pip setuptools
          pip install .[runner]
          echo $PWD
          cd ..
          mkdir -p test/nsys
          echo $PWD
          echo "Running larnd-sim"
          lar_runner.py -y larnd-sim/cli/runner.yaml nsys -o test_ci &> run.log
          echo "Finished"
